# Generated by Django 5.1.5 on 2025-03-15 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_alter_flight_destination_alter_flight_origin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
